# Generated by Django 3.2.5 on 2021-07-24 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sumda', '0002_comment_diary_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='sumda.profile'),
        ),
    ]
