# Generated by Django 3.2.5 on 2021-07-24 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumda', '0003_alter_diary_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='block',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diary',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='일기제목'),
        ),
    ]
