# Generated by Django 3.2.5 on 2021-07-24 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sumda', '0004_auto_20210724_1331'),
        ('sumda', '0004_diary_title'),
    ]

    operations = [
    ]
